version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: crawler_prometheus
    ports:
    - 9090:9090
    volumes:
    - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus_data:/prometheus
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --web.console.templates=/etc/prometheus/consoles
    restart: unless-stopped
    extra_hosts:
    - host.docker.internal:host-gateway
  grafana:
    image: grafana/grafana:latest
    container_name: crawler_grafana
    ports:
    - 3000:3000
    volumes:
    - grafana_data:/var/lib/grafana
    - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
  redis-0:
    image: redis:latest
    container_name: crawler-redis-0
    restart: unless-stopped
    ports:
    - 6379:6379
    volumes:
    - redis-data-0:/data
    - ./logs/redis/pod-0:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 90gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
  redis-1:
    image: redis:latest
    container_name: crawler-redis-1
    restart: unless-stopped
    ports:
    - 6380:6379
    volumes:
    - redis-data-1:/data
    - ./logs/redis/pod-1:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 90gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
  redis-2:
    image: redis:latest
    container_name: crawler-redis-2
    restart: unless-stopped
    ports:
    - 6381:6379
    volumes:
    - redis-data-2:/data
    - ./logs/redis/pod-2:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 90gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
  redis-3:
    image: redis:latest
    container_name: crawler-redis-3
    restart: unless-stopped
    ports:
    - 6382:6379
    volumes:
    - redis-data-3:/data
    - ./logs/redis/pod-3:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 90gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
  redis-4:
    image: redis:latest
    container_name: crawler-redis-4
    restart: unless-stopped
    ports:
    - 6383:6379
    volumes:
    - redis-data-4:/data
    - ./logs/redis/pod-4:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 90gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
  redis-5:
    image: redis:latest
    container_name: crawler-redis-5
    restart: unless-stopped
    ports:
    - 6384:6379
    volumes:
    - redis-data-5:/data
    - ./logs/redis/pod-5:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 90gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
  redis-6:
    image: redis:latest
    container_name: crawler-redis-6
    restart: unless-stopped
    ports:
    - 6385:6379
    volumes:
    - redis-data-6:/data
    - ./logs/redis/pod-6:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 90gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
  redis-7:
    image: redis:latest
    container_name: crawler-redis-7
    restart: unless-stopped
    ports:
    - 6386:6379
    volumes:
    - redis-data-7:/data
    - ./logs/redis/pod-7:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 90gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
  redis-8:
    image: redis:latest
    container_name: crawler-redis-8
    restart: unless-stopped
    ports:
    - 6387:6379
    volumes:
    - redis-data-8:/data
    - ./logs/redis/pod-8:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 90gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
  redis-9:
    image: redis:latest
    container_name: crawler-redis-9
    restart: unless-stopped
    ports:
    - 6388:6379
    volumes:
    - redis-data-9:/data
    - ./logs/redis/pod-9:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 90gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
  redis-10:
    image: redis:latest
    container_name: crawler-redis-10
    restart: unless-stopped
    ports:
    - 6389:6379
    volumes:
    - redis-data-10:/data
    - ./logs/redis/pod-10:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 90gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
  redis-11:
    image: redis:latest
    container_name: crawler-redis-11
    restart: unless-stopped
    ports:
    - 6390:6379
    volumes:
    - redis-data-11:/data
    - ./logs/redis/pod-11:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 90gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
  redis-12:
    image: redis:latest
    container_name: crawler-redis-12
    restart: unless-stopped
    ports:
    - 6391:6379
    volumes:
    - redis-data-12:/data
    - ./logs/redis/pod-12:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 90gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
  redis-13:
    image: redis:latest
    container_name: crawler-redis-13
    restart: unless-stopped
    ports:
    - 6392:6379
    volumes:
    - redis-data-13:/data
    - ./logs/redis/pod-13:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 90gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
  redis-14:
    image: redis:latest
    container_name: crawler-redis-14
    restart: unless-stopped
    ports:
    - 6393:6379
    volumes:
    - redis-data-14:/data
    - ./logs/redis/pod-14:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 90gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
  redis-15:
    image: redis:latest
    container_name: crawler-redis-15
    restart: unless-stopped
    ports:
    - 6394:6379
    volumes:
    - redis-data-15:/data
    - ./logs/redis/pod-15:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 90gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  redis-data-0:
    driver: local
  redis-data-1:
    driver: local
  redis-data-2:
    driver: local
  redis-data-3:
    driver: local
  redis-data-4:
    driver: local
  redis-data-5:
    driver: local
  redis-data-6:
    driver: local
  redis-data-7:
    driver: local
  redis-data-8:
    driver: local
  redis-data-9:
    driver: local
  redis-data-10:
    driver: local
  redis-data-11:
    driver: local
  redis-data-12:
    driver: local
  redis-data-13:
    driver: local
  redis-data-14:
    driver: local
  redis-data-15:
    driver: local
