version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: crawler_prometheus
    ports:
    - 9090:9090
    volumes:
    - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus_data:/prometheus
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --web.console.templates=/etc/prometheus/consoles
    restart: unless-stopped
    extra_hosts:
    - host.docker.internal:host-gateway
  grafana:
    image: grafana/grafana:latest
    container_name: crawler_grafana
    ports:
    - 3000:3000
    volumes:
    - grafana_data:/var/lib/grafana
    - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
  redis-0:
    image: redis:latest
    container_name: crawler-redis-0
    restart: unless-stopped
    ports:
    - 6379:6379
    volumes:
    - redis-data-0:/data
    - ./logs/redis/pod-0:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 360gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
  redis-1:
    image: redis:latest
    container_name: crawler-redis-1
    restart: unless-stopped
    ports:
    - 6380:6379
    volumes:
    - redis-data-1:/data
    - ./logs/redis/pod-1:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 360gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
  redis-2:
    image: redis:latest
    container_name: crawler-redis-2
    restart: unless-stopped
    ports:
    - 6381:6379
    volumes:
    - redis-data-2:/data
    - ./logs/redis/pod-2:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 360gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
  redis-3:
    image: redis:latest
    container_name: crawler-redis-3
    restart: unless-stopped
    ports:
    - 6382:6379
    volumes:
    - redis-data-3:/data
    - ./logs/redis/pod-3:/var/log/redis
    command:
    - redis-server
    - --maxmemory
    - 360gb
    - --maxmemory-policy
    - noeviction
    - --save
    - '900'
    - '1'
    - --save
    - '300'
    - '10'
    - --save
    - '60'
    - '10000'
    - --appendonly
    - 'no'
    - --rdbcompression
    - 'yes'
    - --rdbchecksum
    - 'yes'
    - --dbfilename
    - dump.rdb
    - --stop-writes-on-bgsave-error
    - 'yes'
    - --logfile
    - /var/log/redis/redis.log
    - --loglevel
    - notice
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 5
volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  redis-data-0:
    driver: local
  redis-data-1:
    driver: local
  redis-data-2:
    driver: local
  redis-data-3:
    driver: local
