version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: crawler_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Allows access to host machine

  grafana:
    image: grafana/grafana:latest
    container_name: crawler_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: crawler-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      # Docker will auto-create this directory if it doesn't exist
      - ./logs/redis:/var/log/redis
    command: >
      redis-server
      --maxmemory 24gb
      --maxmemory-policy noeviction
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendonly no
      --rdbcompression yes
      --rdbchecksum yes
      --dbfilename dump.rdb
      --stop-writes-on-bgsave-error yes
      --logfile /var/log/redis/redis.log
      --loglevel notice
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  prometheus_data:
  grafana_data:
  redis-data:
    driver: local 