global:
  scrape_interval: 15s  # How often to scrape metrics
  evaluation_interval: 15s  # How often to evaluate rules

scrape_configs:
  - job_name: 'crawler'
    static_configs:
      - targets: ['host.docker.internal:8001']  # Crawler metrics endpoint
        labels:
          instance: 'main-crawler' 